language: php

sudo: false

matrix:
  include:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6

script:
 - '[[ "$TRAVIS_PHP_VERSION" = 5.2* ]] && phpunit || vendor/bin/phpunit --verbose'

install:
 - '[[ "$TRAVIS_PHP_VERSION" = 5.2* ]] || composer install'
